version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=anytimegridsearch
  backend:
    image: anytime-gridsearch:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    entrypoint: /entrypoint.sh
    depends_on:
      - db