# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 08:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grids', '0006_cvresults_errors'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVResultScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorer', models.CharField(max_length=256)),
                ('train_scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), default=list, size=None)),
                ('test_scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), default=list, size=None)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='cvresult',
            name='cross_validation_scores',
        ),
        migrations.RemoveField(
            model_name='cvresult',
            name='score',
        ),
        migrations.AddField(
            model_name='cvresult',
            name='fit_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), default=list, size=None),
        ),
        migrations.AddField(
            model_name='cvresult',
            name='score_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), default=list, size=None),
        ),
        migrations.AddField(
            model_name='cvresultscore',
            name='cv_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='grids.CVResult'),
        ),
    ]
